### ISSUE TITLE
Avatar generators flexibility

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/avatars#23]
This is  a **feature request**.

Have you consider making the avatars generators configurable?

I mean not only to depend on `App::runningUnitTests()`:

```php
public function create(): Avatar
    {
        return App::runningUnitTests()
            ? $this->laravolt()
            : $this->gravatar()
            ?? $this->laravolt();
    }
```

Some of us may have systems that are off the grid (no internet), and gravatar default generator returns:
```
 Illuminate\Http\Client\ConnectionException

  cURL error 28: Failed to connect to www.gravatar.com port 443: Timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://www.gravatar.com/avatar/55a01a438d7dc704a59b95ecc39c9f0c?size=250&default=404

  at ..\vendor\laravel\framework\src\Illuminate\Http\Client\PendingRequest.php:665
    661▕                         $response->throw();
    662▕                     }
    663▕                 });
    664▕             } catch (ConnectException $e) {
  ➜ 665▕                 throw new ConnectionException($e->getMessage(), 0, $e);
    666▕             }
    667▕         }, $this->retryDelay ?? 100);
    668▕     }
    669▕

  1   ..\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:210
      GuzzleHttp\Exception\ConnectException::("cURL error 28: Failed to connect to www.gravatar.com port 443: Timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://www.gravatar.com/avatar/55a01a438d7dc704a59b95ecc39c9f0c?size=250&default=404")

  2   ..\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:158
      GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle))
```

And this start even in the seeding (User creation).

As always, if you are ok with such change but have not time for it I can contribute. Just let me know if you would accept such flexibility.

**Comment by aocneanu** [comment]
@robbykrlos what do you think about this approach?

```php
        try {
            if (Http::head($this->url())->ok()) {
                $this->avatar->fill(['url' => $this->url()])->save();

                return $this->avatar;
            }

            return null;
        } catch (ConnectionException) {
            return null;
        }
```

**Comment by robbykrlos** [comment]
> @robbykrlos what do you think about this approach?
> 
> ```
>         try {
>             if (Http::head($this->url())->ok()) {
>                 $this->avatar->fill(['url' => $this->url()])->save();
> 
>                 return $this->avatar;
>             }
> 
>             return null;
>         } catch (ConnectionException) {
>             return null;
>         }
> ```

Well... that's just fixing the error - which is ok in the end, and probably it's good to have it in. 

But this is not falling back on Laravolt generator, it's just avoiding avatars entirely if gravatar (the default) fails (because of the null return). Right? 

I was trying to suggest a configurable Gravatar generator (2 options : 1 Gravatar (default) , 2 Laravolt).

Or, if extra configurations / options are not wanted, maybe an additional check ?

```php
public function create(): Avatar
    {
        return App::runningUnitTests() || ! $this->isGravatarReachable()
            ? $this->laravolt()
            : $this->gravatar()
            ?? $this->laravolt();
    }
```

Because, in the end, it's still nice to have an avatar generated by Laravolt/Avatar - even with some letters/initials, then have nothing - if you don't have internet access.

Let me know how you want to go, I can help either way with a PR.

**Comment by aocneanu** [comment]
@robbykrlos right now we have

```php
return App::runningUnitTests()
            ? $this->laravolt()
            : $this->gravatar()
            ?? $this->laravolt();
```

If we're running tests we use laravolt. if not we use gravatar or if null again laravolt.

Am I missing something?

**Comment by robbykrlos** [comment]
@aocneanu the problem we are facing this this implementation is that we have systems that do not have internet connection, therefore gravatar is not accessible. This usually translates in errors like : "Seeding error : cURL error 28: Failed to connect to www.gravatar.com port 443: Timed out" when running the seeders, or when creating a new user.

My suggestion was if there can be a fallback on laravolt in case gravatar is not reachable.

**Comment by robbykrlos** [comment]
@aocneanu I just realized I was blind not seeing this fallback:
```php
: $this->gravatar()
?? $this->laravolt();
```
Thanks!

I only need to figure out a way to limit the timeout, since seeding takes 60+ sec.
