### ISSUE TITLE
Broken avatars on database restore (with laravolt/avatar) [minor]

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/avatars#24]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
To setup the context, on our side we only use laravolt avatars, so no gravatars.
As I see, there is a slight different approach between laravolt avatars and gravatars. Avatars table contains a URL, which I believe is filled up when using gravatar, but not when using laravolt avatars. I also see that laravolt avatars are stored inside storage/app/avatars.

### Steps to Reproduce
Import a different database.
Check users table. Avatars will look like:

![image](https://user-images.githubusercontent.com/16973022/133265005-8e5cb1ac-b928-45ad-b2ba-c14ee458be8a.png)

Only newly created users will get a new correct avatar.

I've tried using `enso:avatars:generate` but this one does not work, and the reason is that this query:
```php
User::doesntHave('avatar')->get()
```
does not return anything. That's because the database has all the relations set inside the avatars table:
![image](https://user-images.githubusercontent.com/16973022/133265802-616ee431-027b-4d94-ada8-2fe4a9083b92.png)
therefore, the relations exists.

My thought are that the laravolt/avatars are not checked correctly. Although it may apply in gravatar's case too.

This is a minor issue since, on our side we can always use an alter `enso:avatars:generate` like :
```php
User::get()->each->generateAvatar();
```
which will force avatars to be regenerated and created inside storage/app/avatars.

**Comment by aocneanu** [comment]
I'm not sure that I understand what the problem is, exactly.

If you import a database that has entries in the files or the documents table(s), they won't work unless you copy the storage folder too.

Enso is built having in mind private environments. All the files are served through controllers that are behind auth middleware.

To use gravatar, which is public, we have to use an URL instead of a local stored file.

**Comment by robbykrlos** [comment]
> I'm not sure that I understand what the problem is, exactly.
> 
> If you import a database that has entries in the files or the documents table(s), they won't work unless you copy the storage folder too.
> 
> Enso is built having in mind private environments. All the files are served through controllers that are behind auth middleware.
> 
> To use gravatar, which is public, we have to use an URL instead of a local stored file.

Tbh I did not yet fully understand the HasFile / attachable part of the Avatar. But I did not know that importing a DB needs also it's storage files. 

Having this clarified, now it is clear why the problem of not seeing avatar images from a newly imported DB is happening. 

Thanks for the explanation. No bug then.
